// Logo colour + core job + taboo word = company.
// Taboo word rule: a sideways hint, never a giveaway. It must NOT be a product or sub-brand (iPhone, Galaxy),
// a founder or famous exec (Elon, Ratan), a slogan, mascot or logo (Just Do It, Swoosh, Colonel), or any word
// from the company's own name. Good: origin city/country, a history fact, a habit people associate with it.
// Logos and brand colours (hex) come from Simple Icons (CC0, simpleicons.org); `slug` is the icon name there.
// Cards without a slug have no logo there: the reveal shows the company's initials on its brand colour (hex set by hand).
export type TabooCard = { company: string; slug?: string; hex: string; job: string; word: string };

export const SIMPLE_ICONS = 'https://cdn.jsdelivr.net/npm/simple-icons@16.33.0/icons';

export const CARDS: TabooCard[] = [
  { company: "Swiggy", slug: 'swiggy', hex: '#FC8019', job: "Food delivery", word: "Late-night cravings" },
  { company: "Zomato", slug: 'zomato', hex: '#E23744', job: "Restaurant discovery & delivery", word: "Gurugram" },
  { company: "Paytm", slug: 'paytm', hex: '#20336B', job: "Digital wallet & payments", word: "Noida" },
  { company: "PhonePe", slug: 'phonepe', hex: '#5F259F', job: "UPI payments app", word: "Spin-off" },
  { company: "Razorpay", slug: 'razorpay', hex: '#0C2451', job: "Payment gateway for businesses", word: "Y Combinator" },
  { company: "Zerodha", slug: 'zerodha', hex: '#387ED1', job: "Stock broking", word: "Discount" },
  { company: "OYO", slug: 'oyo', hex: '#EE2E24', job: "Budget hotel rooms", word: "Dropout" },
  { company: "BookMyShow", slug: 'bookmyshow', hex: '#C4242B', job: "Movie & event tickets", word: "Weekend plans" },
  { company: "boAt", slug: 'boat', hex: '#E20722', job: "Audio wearables", word: "Gym" },
  { company: "BYJU'S", slug: 'byjus', hex: '#813588', job: "Learning app for students", word: "Kerala" },
  { company: "Unacademy", slug: 'unacademy', hex: '#08BD80', job: "Online exam prep classes", word: "Doubts" },
  { company: "Zoho", slug: 'zoho', hex: '#E42527', job: "Business software suite", word: "Bootstrapped" },
  { company: "Amul", slug: 'amul', hex: '#ED1D24', job: "Dairy products", word: "Cooperative" },
  { company: "Tata Group", slug: 'tata', hex: '#486AAE', job: "Salt to software conglomerate", word: "Trust" },
  { company: "Mahindra", slug: 'mahindra', hex: '#DD052B', job: "SUVs & tractors", word: "Farmers" },
  { company: "Jio", slug: 'jio', hex: '#0A2885', job: "Mobile network & data", word: "2016" },
  { company: "Airtel", slug: 'airtel', hex: '#E40000', job: "Mobile network & broadband", word: "Africa" },
  { company: "IndiGo", slug: 'indigo', hex: '#09009B', job: "Low-cost airline", word: "On time" },
  { company: "Infosys", slug: 'infosys', hex: '#007CC3', job: "IT services", word: "Campus" },
  { company: "Wipro", slug: 'wipro', hex: '#341C53', job: "IT services", word: "Vegetable oil" },
  { company: "HCL", slug: 'hcl', hex: '#006BB6', job: "IT services & hardware", word: "Calculators" },
  { company: "HDFC Bank", slug: 'hdfcbank', hex: '#004B8D', job: "Private bank", word: "Mumbai" },
  { company: "ICICI Bank", slug: 'icicibank', hex: '#AE282E', job: "Private bank", word: "Vadodara" },
  { company: "Dunzo", slug: 'dunzo', hex: '#00D290', job: "Quick commerce & errands", word: "Shut down" },
  { company: "Google", slug: 'google', hex: '#4285F4', job: "Search engine", word: "Verb" },
  { company: "Apple", slug: 'apple', hex: '#000000', job: "Phones & laptops", word: "Cupertino" },
  { company: "Netflix", slug: 'netflix', hex: '#E50914', job: "Streaming movies & shows", word: "DVDs" },
  { company: "YouTube", slug: 'youtube', hex: '#FF0000', job: "Video sharing", word: "Rabbit hole" },
  { company: "Spotify", slug: 'spotify', hex: '#1ED760', job: "Music streaming", word: "Sweden" },
  { company: "Instagram", slug: 'instagram', hex: '#FF0069', job: "Photo & reels sharing", word: "Influencer" },
  { company: "WhatsApp", slug: 'whatsapp', hex: '#25D366', job: "Messaging app", word: "Family group" },
  { company: "X (Twitter)", slug: 'x', hex: '#000000', job: "Short posts social network", word: "280" },
  { company: "TikTok", slug: 'tiktok', hex: '#000000', job: "Short video app", word: "Banned in India" },
  { company: "Uber", slug: 'uber', hex: '#000000', job: "Ride hailing", word: "Surge" },
  { company: "Airbnb", slug: 'airbnb', hex: '#FF5A5F', job: "Home stays", word: "Air mattress" },
  { company: "Tesla", slug: 'tesla', hex: '#CC0000', job: "Electric cars", word: "Serbian inventor" },
  { company: "SpaceX", slug: 'spacex', hex: '#000000', job: "Rockets & launches", word: "Reusable" },
  { company: "Nvidia", slug: 'nvidia', hex: '#76B900', job: "Graphics & AI chips", word: "Leather jacket" },
  { company: "Zoom", slug: 'zoom', hex: '#0B5CFF', job: "Video meetings", word: "Lockdown" },
  { company: "Notion", slug: 'notion', hex: '#000000', job: "Notes & docs workspace", word: "Second brain" },
  { company: "Figma", slug: 'figma', hex: '#F24E1E', job: "Collaborative design tool", word: "Multiplayer" },
  { company: "Stripe", slug: 'stripe', hex: '#635BFF', job: "Online payments API", word: "Irish brothers" },
  { company: "PayPal", slug: 'paypal', hex: '#002991', job: "Online payments", word: "eBay" },
  { company: "Duolingo", slug: 'duolingo', hex: '#58CC02', job: "Language learning", word: "Streak" },
  { company: "Shopify", slug: 'shopify', hex: '#7AB55C', job: "Online store builder", word: "Canada" },
  { company: "Samsung", slug: 'samsung', hex: '#1428A0', job: "Phones & electronics", word: "Korea" },
  { company: "Nike", slug: 'nike', hex: '#111111', job: "Sportswear", word: "Greek goddess" },
  { company: "Adidas", slug: 'adidas', hex: '#000000', job: "Sportswear", word: "Germany" },
  { company: "IKEA", slug: 'ikea', hex: '#0058A3', job: "Flat-pack furniture", word: "Allen key" },
  { company: "Starbucks", slug: 'starbucks', hex: '#006241', job: "Coffee chain", word: "Misspelled names" },
  { company: "McDonald's", slug: 'mcdonalds', hex: '#FBC817', job: "Fast food burgers", word: "Drive-thru" },
  { company: "KFC", slug: 'kfc', hex: '#F40027', job: "Fried chicken", word: "Secret recipe" },
  { company: "Coca-Cola", slug: 'cocacola', hex: '#D00013', job: "Soft drinks", word: "Atlanta" },
  { company: "Red Bull", slug: 'redbull', hex: '#DB0A40', job: "Energy drinks", word: "Extreme sports" },
  { company: "Ferrari", slug: 'ferrari', hex: '#D40000', job: "Supercars", word: "Italy" },
  { company: "Facebook", slug: 'facebook', hex: '#0866FF', job: "Social network", word: "Harvard" },
  { company: "Snapchat", slug: 'snapchat', hex: '#FFFC00', job: "Disappearing photo messages", word: "Dog filter" },
  { company: "Pinterest", slug: 'pinterest', hex: '#BD081C', job: "Visual idea boards", word: "Wedding ideas" },
  { company: "Reddit", slug: 'reddit', hex: '#FF4500', job: "Online forums", word: "AMA" },
  { company: "Discord", slug: 'discord', hex: '#5865F2', job: "Community voice & chat", word: "Gamers" },
  { company: "Twitch", slug: 'twitch', hex: '#9146FF', job: "Live game streaming", word: "Emotes" },
  { company: "GitHub", slug: 'github', hex: '#181717', job: "Code hosting", word: "Open source" },
  { company: "Xiaomi", slug: 'xiaomi', hex: '#FF6900', job: "Budget smartphones", word: "China" },
  { company: "Intel", slug: 'intel', hex: '#0071C5', job: "Computer processors", word: "Moore's law" },
  { company: "Visa", slug: 'visa', hex: '#1A1F71', job: "Card payments network", word: "Swipe" },
  { company: "Mastercard", slug: 'mastercard', hex: '#EB001B', job: "Card payments network", word: "Debit" },
  { company: "Toyota", slug: 'toyota', hex: '#EB0A1E', job: "Cars", word: "Japan" },
  { company: "BMW", slug: 'bmw', hex: '#0066B1', job: "Luxury cars", word: "Munich" },
  { company: "PlayStation", slug: 'playstation', hex: '#0070D1', job: "Gaming console", word: "Controller" },
  { company: "Burger King", slug: 'burgerking', hex: '#D62300', job: "Fast food burgers", word: "Flame-grilled" },
  { company: "Dropbox", slug: 'dropbox', hex: '#0061FF', job: "Cloud file storage", word: "Shared folder" },
  { company: "Telegram", slug: 'telegram', hex: '#26A5E4', job: "Messaging app", word: "Privacy" },
  { company: "Booking.com", slug: 'bookingdotcom', hex: '#003A9A', job: "Hotel bookings", word: "Amsterdam" },
  { company: "Tinder", slug: 'tinder', hex: '#FF6B6B', job: "Dating app", word: "Ghosting" },
  // India (more)
  { company: "Flipkart", hex: '#2874F0', job: "Online marketplace", word: "Walmart" },
  { company: "Myntra", hex: '#FF3F6C', job: "Online fashion store", word: "Wardrobe" },
  { company: "Nykaa", hex: '#FC2779', job: "Beauty & cosmetics e-commerce", word: "Ex-banker" },
  { company: "Lenskart", hex: '#00BAC6', job: "Eyewear retail", word: "Eye test" },
  { company: "CRED", hex: '#111111', job: "Credit card bill rewards", word: "Exclusive club" },
  { company: "Groww", hex: '#00D09C', job: "Investing app", word: "SIP" },
  { company: "Upstox", hex: '#5A298B', job: "Stock trading app", word: "Demat" },
  { company: "Meesho", hex: '#F43397', job: "Social reselling marketplace", word: "Homemakers" },
  { company: "Zepto", hex: '#3C006B', job: "Quick grocery delivery", word: "Stanford dropouts" },
  { company: "Blinkit", hex: '#F8CB46', job: "Instant delivery app", word: "Rebranded" },
  { company: "BigBasket", slug: 'bigbasket', hex: '#A5CD39', job: "Online grocery store", word: "Tata-owned" },
  { company: "Ola", hex: '#111111', job: "Cabs & e-scooters", word: "Auto-rickshaw" },
  { company: "Rapido", hex: '#F9C935', job: "Bike taxi", word: "Pillion" },
  { company: "MakeMyTrip", hex: '#EB2026', job: "Online travel booking", word: "Holiday packages" },
  { company: "redBus", hex: '#D84E55', job: "Bus ticket booking", word: "Overnight journey" },
  { company: "Dream11", hex: '#CF2027', job: "Fantasy sports", word: "IPL" },
  { company: "Disney+ Hotstar", hex: '#1F80E0', job: "Streaming service", word: "Cricket" },
  { company: "Practo", hex: '#14BEF0', job: "Doctor appointments", word: "Clinic" },
  { company: "PharmEasy", hex: '#10847E', job: "Online pharmacy", word: "Prescription" },
  { company: "Urban Company", hex: '#111111', job: "Home services", word: "Plumber" },
  { company: "Naukri", hex: '#457EFF', job: "Job portal", word: "Resume" },
  { company: "Snapdeal", hex: '#E40046', job: "Value e-commerce", word: "Delhi" },
  { company: "Tata Motors", hex: '#486AAE', job: "Cars & trucks", word: "Safety rating" },
  { company: "TCS", slug: 'tcs', hex: '#EE3984', job: "IT consulting", word: "Largest IT employer" },
  { company: "Hero MotoCorp", hex: '#E31E24', job: "Two-wheelers", word: "Largest bike maker" },
  { company: "Bajaj Auto", hex: '#005CA9', job: "Motorcycles & three-wheelers", word: "Pune" },
  { company: "TVS Motor", hex: '#1B3E93', job: "Motorcycles & scooters", word: "Chennai" },
  { company: "Maruti Suzuki", hex: '#1F3E8C', job: "Family cars", word: "800" },
  { company: "SBI", hex: '#22409A', job: "Public sector bank", word: "Largest bank" },
  { company: "Bank of Baroda", hex: '#F15A22', job: "Government bank", word: "Gujarat" },
  { company: "Kotak Mahindra Bank", hex: '#ED1C24', job: "Bank & stock broking", word: "Zero-balance" },
  { company: "Axis Bank", hex: '#97144D', job: "Private bank & cards", word: "Ahmedabad" },
  { company: "LIC", hex: '#0072BC', job: "Life insurance", word: "Government" },
  { company: "Policybazaar", hex: '#0D4DA1', job: "Insurance comparison", word: "Compare" },
  { company: "Postman", slug: 'postman', hex: '#FF6C37', job: "API testing tool", word: "Developers" },
  { company: "SUGAR Cosmetics", hex: '#111111', job: "Makeup brand", word: "Bold" },
  { company: "Parle", hex: '#E2231A', job: "Biscuits & candy", word: "Since 1929" },
  { company: "Britannia", hex: '#D71920', job: "Biscuits & bread", word: "Kolkata" },
  { company: "Haldiram's", hex: '#E31E24', job: "Snacks & sweets", word: "Nagpur" },
  { company: "MTR", slug: 'mtr', hex: '#AC2E45', job: "Ready-to-eat food", word: "Bengaluru" },
  { company: "Dabur", hex: '#00953B', job: "Herbal health products", word: "Ayurveda" },
  { company: "Patanjali", hex: '#F7A600', job: "Herbal FMCG", word: "Yoga" },
  { company: "Hindustan Unilever", hex: '#1F36C7', job: "Soaps & household goods", word: "FMCG" },
  { company: "Bisleri", hex: '#00A651', job: "Bottled water", word: "Mineral" },
  { company: "Air India", hex: '#DA0A0A', job: "National airline", word: "1932" },
  { company: "SpiceJet", hex: '#E21F26', job: "Budget airline", word: "Low fares" },
  { company: "Akasa Air", hex: '#FF6A13', job: "New budget airline", word: "2022" },
  { company: "Havells", slug: 'havells', hex: '#ED1C24', job: "Electricals & fans", word: "Wires" },
  { company: "Tanishq", hex: '#832729', job: "Jewellery brand", word: "Wedding" },
  { company: "Kingfisher", hex: '#E3001B', job: "Beer brand", word: "Calendar" },
  { company: "Indian Oil", hex: '#F37022', job: "Fuel stations", word: "Refinery" },
  { company: "JioCinema", hex: '#D9008D', job: "Streaming app", word: "Free streaming" },
  { company: "MagicBricks", hex: '#D8232A', job: "Property listings", word: "Rent" },
  { company: "Ixigo", hex: '#FC790D', job: "Train & flight booking", word: "PNR" },
  { company: "Cleartrip", hex: '#FF4F17', job: "Flight booking", word: "Flipkart-owned" },
  { company: "upGrad", hex: '#E31E24', job: "Online degrees", word: "Working professionals" },
  { company: "Pepperfry", hex: '#F16521', job: "Online furniture", word: "Sofa" },
  { company: "Licious", hex: '#E3242B', job: "Meat delivery", word: "Fresh cuts" },
  { company: "Tech Mahindra", hex: '#E31837', job: "IT services", word: "Satyam" },
  { company: "Thums Up", hex: '#E21B22', job: "Cola drink", word: "Strong fizz" },
  // Global (more)
  { company: "eBay", slug: 'ebay', hex: '#E53238', job: "Online auctions", word: "Garage sale" },
  { company: "Ford", slug: 'ford', hex: '#00274E', job: "Cars & pickup trucks", word: "Assembly line" },
  { company: "Audi", slug: 'audi', hex: '#BB0A30', job: "Luxury cars", word: "Ingolstadt" },
  { company: "Lamborghini", slug: 'lamborghini', hex: '#B6A272', job: "Supercars", word: "Tractors" },
  { company: "Volvo", slug: 'volvo', hex: '#003057', job: "Safe cars", word: "Seatbelt" },
  { company: "Porsche", slug: 'porsche', hex: '#B12B28', job: "Sports cars", word: "Beetle" },
  { company: "Volkswagen", slug: 'volkswagen', hex: '#151F5D', job: "Cars", word: "Emissions scandal" },
  { company: "Boeing", slug: 'boeing', hex: '#1D439C', job: "Aircraft maker", word: "Seattle" },
  { company: "Airbus", slug: 'airbus', hex: '#00205B', job: "Aircraft maker", word: "Europe" },
  { company: "Emirates", slug: 'emirates', hex: '#D71921', job: "Airline", word: "Dubai" },
  { company: "DHL", slug: 'dhl', hex: '#FFCC00', job: "Courier & logistics", word: "Express parcel" },
  { company: "FedEx", slug: 'fedex', hex: '#4D148C', job: "Courier & logistics", word: "Overnight" },
  { company: "Shell", slug: 'shell', hex: '#FFD500', job: "Fuel stations", word: "Anglo-Dutch" },
  { company: "Siemens", slug: 'siemens', hex: '#009999', job: "Engineering & electronics", word: "Trains" },
  { company: "Bosch", slug: 'bosch', hex: '#EA0016', job: "Appliances & auto parts", word: "Spark plug" },
  { company: "Audible", slug: 'audible', hex: '#F8991C', job: "Audiobooks", word: "Commute" },
  { company: "LG", slug: 'lg', hex: '#A50034', job: "Electronics & appliances", word: "Washing machine" },
  { company: "Sony", slug: 'sony', hex: '#FFFFFF', job: "Electronics & entertainment", word: "Tokyo" },
  { company: "Lenovo", slug: 'lenovo', hex: '#E2231A', job: "Laptops & PCs", word: "Beijing" },
  { company: "Dell", slug: 'dell', hex: '#007DB8', job: "Computers", word: "Dorm room" },
  { company: "HP", slug: 'hp', hex: '#0096D6', job: "Printers & PCs", word: "Garage" },
  { company: "Cisco", slug: 'cisco', hex: '#1BA0D7', job: "Networking equipment", word: "Routers" },
  { company: "Steam", slug: 'steam', hex: '#000000', job: "PC game store", word: "Wishlist" },
  { company: "Roblox", slug: 'roblox', hex: '#000000', job: "Kids’ game platform", word: "Avatar" },
  { company: "Etsy", slug: 'etsy', hex: '#F16521', job: "Handmade marketplace", word: "Crafts" },
  { company: "Wikipedia", slug: 'wikipedia', hex: '#000000', job: "Online encyclopedia", word: "Donations" },
  { company: "Quora", slug: 'quora', hex: '#B92B27', job: "Q&A site", word: "Anonymous" },
  { company: "Firefox", slug: 'firefox', hex: '#FF7139', job: "Web browser", word: "Non-profit" },
  { company: "Coinbase", slug: 'coinbase', hex: '#0052FF', job: "Crypto exchange", word: "Bitcoin" },
  { company: "Robinhood", slug: 'robinhood', hex: '#CCFF00', job: "Free stock trading", word: "GameStop" },
  { company: "Fitbit", slug: 'fitbit', hex: '#00B0B9', job: "Fitness trackers", word: "10,000 steps" },
  { company: "Peloton", slug: 'peloton', hex: '#181A1D', job: "Home exercise bikes", word: "Pandemic" },
  { company: "Zara", slug: 'zara', hex: '#000000', job: "Fast fashion", word: "Spain" },
  { company: "Uniqlo", slug: 'uniqlo_ja', hex: '#FF0000', job: "Basics clothing", word: "Minimal" },
  { company: "Udemy", slug: 'udemy', hex: '#A435F0', job: "Online courses", word: "Coupon" },
  { company: "Coursera", slug: 'coursera', hex: '#0056D2', job: "University courses online", word: "Stanford" },
  { company: "WordPress", slug: 'wordpress', hex: '#21759B', job: "Website builder", word: "Blog" },
  { company: "Tripadvisor", slug: 'tripadvisor', hex: '#34E0A1', job: "Travel reviews", word: "Hidden gems" },
  { company: "Jeep", slug: 'jeep', hex: '#000000', job: "Off-road vehicles", word: "WWII" },
  { company: "Puma", slug: 'puma', hex: '#242B2F', job: "Sportswear", word: "Feud" },
];
